//tag::ref-doc[]
= TaskLauncher Data Flow Sink

This application launches a registered task application using the Data Flow Server http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-launching[REST API].

== Input

Launch request parameters including:

* the task name (required and registered as a task with the target Data Flow Server)
* deployment properties (key value pairs, optional).
* program arguments for the task (a list, optional).

=== Headers:

* `Content-Type: application/json`

=== Payload:

A JSON document:

[source,json]
----
{
  "name":"foo",
  "deploymentProps": {"key1":"val1","key2":"val2"},
  "args":["--debug", "--foo", "bar"]
}
----

minimally,

[source,json]
----
{"name":"foo"}
----

== Output

N/A (launches task to the local system).

=== Options

The **$$tasklauncher-dataflow$$** $$sink$$ supports the following configuration properties:

//tag::configuration-properties[]
$$spring.cloud.dataflow.client.authentication.basic.password$$:: $$The login password.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.cloud.dataflow.client.authentication.basic.username$$:: $$The login username.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.cloud.dataflow.client.enable-dsl$$:: $$Enable Data Flow DSL access.$$ *($$Boolean$$, default: `$$false$$`)*
$$spring.cloud.dataflow.client.server-uri$$:: $$The Data Flow server URI.$$ *($$String$$, default: `$$http://localhost:9393$$`)*
$$spring.cloud.dataflow.client.skip-ssl-validation$$:: $$Skip Ssl validation.$$ *($$Boolean$$, default: `$$true$$`)*
$$trigger.fixed-delay$$:: $$The fixed delay (polling interval).$$ *($$Integer$$, default: `$$1$$`)*
$$trigger.initial-delay$$:: $$The initial delay.$$ *($$Integer$$, default: `$$1$$`)*
$$trigger.time-unit$$:: $$The TimeUnit to apply to delay values.$$ *($$TimeUnit$$, default: `$$<none>$$`, possible values: `NANOSECONDS`,`MICROSECONDS`,`MILLISECONDS`,`SECONDS`,`MINUTES`,`HOURS`,`DAYS`)*
//end::configuration-properties[]

== Using the TaskLauncher
A tasklauncher is a sink that consumes a `LaunchRequest` message, as described above, and launches the task on a
target Spring Cloud Data Flow server (given by `--dataflow.uri`). The task launcher sink polls its input for launch
requests but will pause when the SCDF server's task execution limit, `spring.cloud.dataflow.task
.maximum-concurrent-tasks`
is reached (see the
http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-task-limit-concurrent-executions[reference docs] for more details).

When the number of running tasks drops below this limit, the sink will resume processing. This is intended to prevent
the SCDF deployment platform from running out of resources under heavy task demand. The polling sink is also
scheduled with a `DynamicPeriodicTrigger`. By default the maximum launch request rate is 1 per second, but may be
configured to any duration. When paused, the trigger period will increase, applying exponential backoff, up to 8
times the configured delay.


NOTE: Pausing the polling puts pressure
 on the message broker so some tuning will be necessary, in extreme cases, to balance resource utilization.


== Build

[source,bash]
----
$ ./mvnw clean install -PgenerateApps
$ cd apps
----

You can find the corresponding binder based projects here. You can then cd into one one of the folders and
build it:

[source,bash]
----
$ ./mvnw clean package
----

=== Examples

Register a task app and create a task, the
https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-samples/timestamp[timestamp sample]
provides a simple demonstration.

[source,bash]
----
dataflow:>app register --name timestamp --type task --uri ...
dataflow:>stream create http | task-launcher-dataflow-sink --deploy
----

Send a launch request,

[source,bash]
----
$curl http://localhost:<port> -H"Content-Type:application/json" -d '{"name":"timestamp"}'
----

[source,bash]
----
dataflow:>task execution list
╔═════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║Task Name│ID│         Start Time         │          End Time          │Exit Code║
╠═════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║timestamp│1 │Fri Aug 10 08:48:05 EDT 2018│Fri Aug 10 08:48:05 EDT 2018│0        ║
╚═════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
----

//end::ref-doc[]
