//tag::ref-doc[]
= TaskLauncher Data Flow Sink

This application launches a registered task application using the Data Flow Server http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-launching[REST API].

== Input

Launch request args including:

* the task name (required and registered as a task with the target Data Flow Server)
* deployment properties (key value pairs, optional).
* program arguments for the task (a list, optional).

=== Headers:

* `Content-Type: application/json`

=== Payload:

A JSON document:

[source,json]
----
{
  "name":"foo",
  "deploymentProps": {"key1":"val1","key2":"val2"},
  "args":["--debug", "--foo", "bar"]
}
----

minimally,

[source,json]
----
{"name":"foo"}
----

== Output

N/A (launches task to the local system).

=== Options

The **$$tasklauncher-dataflow$$** $$sink$$ supports the following configuration properties:

//tag::configuration-properties[]
$$spring.cloud.dataflow.client.authentication.basic.password$$:: $$The login password.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.cloud.dataflow.client.authentication.basic.username$$:: $$The login username.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.cloud.dataflow.client.enable-dsl$$:: $$Enable Data Flow DSL access.$$ *($$Boolean$$, default: `$$false$$`)*
$$spring.cloud.dataflow.client.server-uri$$:: $$The Data Flow server URI.$$ *($$String$$, default: `$$http://localhost:9393$$`)*
$$spring.cloud.dataflow.client.skip-ssl-validation$$:: $$Skip Ssl validation.$$ *($$Boolean$$, default: `$$true$$`)*
$$trigger.initial-delay$$:: $$The initial delay in milliseconds.$$ *($$Integer$$, default: `$$1000$$`)*
$$trigger.max-period$$:: $$The maximum polling period in milliseconds. Will be set to period if period > maxPeriod.$$ *($$Integer$$, default: `$$30000$$`)*
$$trigger.period$$:: $$The polling period in milliseconds.$$ *($$Integer$$, default: `$$1000$$`)*
//end::configuration-properties[]

== Using the TaskLauncher
A tasklauncher is a sink that consumes  `LaunchRequest` messages, as described above, and launches a task using the
configured Spring Cloud Data Flow server (given by `--dataflow.uri`). The task launcher periodically polls its input
for launch requests but will pause when the SCDF server's concurrent task execution limit given by `spring.cloud
.dataflow.task
.maximum-concurrent-tasks`
is reached (see the
http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-task-limit-concurrent-executions[reference docs] for more details).

When the number of running tasks drops below this limit message polling resumes. This is intended to prevent
the SCDF deployer's deployment platform from running out of resources under heavy task load. The poller is
scheduled using a `DynamicPeriodicTrigger`. By default the polling rate is 1 second, but may be
configured to any duration. When paused, or if there are no launch requests, the trigger period will increase, applying
exponential backoff, up to a configured maximum (30 seconds by default).


NOTE: When the poller is paused it puts pressure
 on the message broker so some tuning will be necessary in extreme cases to balance resource utilization.

== Build

[source,bash]
----
$ ./mvnw clean install -PgenerateApps
$ cd apps
----

You can find the corresponding binder based projects here. You can then cd into one one of the folders and
build it:

[source,bash]
----
$ ./mvnw clean package
----

=== Examples

Register a task app and create a task, the
https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-samples/timestamp[timestamp sample]
provides a simple demonstration.

[source,bash]
----
dataflow:>app register --name timestamp --type task --uri ...
dataflow:>stream create http | task-launcher-dataflow-sink --deploy
----

Send a launch request,

[source,bash]
----
$curl http://localhost:<port> -H"Content-Type:application/json" -d '{"name":"timestamp"}'
----

[source,bash]
----
dataflow:>task execution list
╔═════════╤══╤════════════════════════════╤════════════════════════════╤═════════╗
║Task Name│ID│         Start Time         │          End Time          │Exit Code║
╠═════════╪══╪════════════════════════════╪════════════════════════════╪═════════╣
║timestamp│1 │Fri Aug 10 08:48:05 EDT 2018│Fri Aug 10 08:48:05 EDT 2018│0        ║
╚═════════╧══╧════════════════════════════╧════════════════════════════╧═════════╝
----

//end::ref-doc[]
